version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_model
    ports:
      - "3000:8000"
    volumes:
      - .:/app
      - ./public:/app/public
    command: >
      uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --log-level info
