<?php

namespace App\Http\Requests\ChannelMessages;

use Illuminate\Foundation\Http\FormRequest;

class UploadAttachmentRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            // if you are receiving an actual file:
            // 'file' => 'required|file|max:10240|mimes:jpg,jpeg,png,gif,webp,pdf,mp4,mp3,zip',
            // otherwise (URL already generated by storage service):
            'file_url'  => 'required|url',
            'file_type' => 'required|string|max:50',
        ];
    }
}
